#!/bin/sh

# Wrapper for nvptx-none-run.

# Copyright (C) 2015 Mentor Graphics

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with nvptx-tools; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.  */

# Invoke nvptx-none-run, locked, such that system-wide only one instance of it
# is running at a time.

nvptx_run=${0%-single}

exec \
flock \
  /tmp/nvptx-run \
  "$nvptx_run" "$@"
